name: PureChat
main: _64FF00\PureChat\PureChat
version: "1.3.4"
api: [1.13.0, 2.0.0]
load: POSTWORLD
author: 64FF00
website: https://github.com/PurePlugins/PureChat
depend: [PurePerms]
softdepend: [FactionsPro]
commands:
  pcreload:
    description: "Reloads the PureChat configuration file."
    permission: pchat.command.pcreload
permissions:
  pchat:
    description: "PureChat by 64FF00! (Twitter: @64FF00)"
    children:
      pchat.colored:
        description: "Allows the players to get colored chat formats, nametags, and more."
        children:
          pchat.colored.chat:
            description: "Allows the players to use color codes"
          pchat.colored.format:
            description: "Allows the players to use colored chat formats"       
          pchat.colored.nametag:
            description: "Allows the players to use colored nametags"
      pchat.command:
        description: "Allows you to use all PureChat commands."
        children:
          pchat.command.pcreload:		
            description: "Allows you to reload PureChat configuration file."
